#!/bin/bash

set -o errexit

set -o pipefail

set -o nounset

postgres_ready() {
echo "POSTGRES_DB: ${POSTGRES_DB}"
echo "POSTGRES_USER: ${POSTGRES_USER}"
echo "POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}"
echo "PG_HOST: ${PG_HOST}"
echo "PG_PORT: ${PG_PORT}"
python << END
import sys
import psycopg2

try:
    psycopg2.connect(
        dbname="${POSTGRES_DB}",
        user="${POSTGRES_USER}",
        password="${POSTGRES_PASSWORD}",
        host="${PG_HOST}",
        port="${PG_PORT}",    
    )
except psycopg2.OperationalError as e:
    print(f"Connection failed: {e}")
    sys.exit(-1)
sys.exit(0)
END
}

max_attempts=30  # Adjust this as needed
attempt=1

until postgres_ready || [ $attempt -eq $max_attempts ]; do
 >&2 echo "Waiting for PostgreSQL to become available....:-("
 sleep 1
attempt=$((attempt+1))
done
>&2 echo "PostgreSQL is ready!!!!...:-)"

exec "$@"